export const INITIAL_SCHEMA_SQL = [
  "CREATE TABLE IF NOT EXISTS workflows (",
  "  id TEXT PRIMARY KEY,",
  "  name TEXT NOT NULL,",
  "  policy_json TEXT NOT NULL DEFAULT '{}',",
  "  active INTEGER NOT NULL DEFAULT 1,",
  "  created_at TEXT NOT NULL,",
  "  updated_at TEXT NOT NULL",
  ");",
  "CREATE TABLE IF NOT EXISTS workflow_versions (",
  "  id TEXT PRIMARY KEY,",
  "  workflow_id TEXT NOT NULL REFERENCES workflows(id),",
  "  version INTEGER NOT NULL,",
  "  ir_json TEXT NOT NULL,",
  "  created_at TEXT NOT NULL",
  ");",
  "CREATE TABLE IF NOT EXISTS executions (",
  "  id TEXT PRIMARY KEY,",
  "  workflow_id TEXT,",
  "  workflow_version INTEGER,",
  "  ephemeral INTEGER NOT NULL DEFAULT 0,",
  "  status TEXT NOT NULL,",
  "  started_at TEXT NOT NULL,",
  "  finished_at TEXT,",
  "  error_code TEXT,",
  "  log_json TEXT NOT NULL DEFAULT '[]',",
  "  trigger_type TEXT,",
  "  ir_json TEXT,",
  "  workspace_session_id TEXT",
  ");",
  "CREATE TABLE IF NOT EXISTS approvals (",
  "  id TEXT PRIMARY KEY,",
  "  execution_id TEXT NOT NULL REFERENCES executions(id),",
  "  action_ids_json TEXT NOT NULL,",
  "  reason TEXT NOT NULL,",
  "  status TEXT NOT NULL DEFAULT 'pending',",
  "  created_at TEXT NOT NULL,",
  "  resolved_at TEXT,",
  "  payload_json TEXT",
  ");",
  "CREATE TABLE IF NOT EXISTS settings (",
  "  key TEXT PRIMARY KEY,",
  "  value_json TEXT NOT NULL",
  ");",
  "CREATE TABLE IF NOT EXISTS connections (",
  "  connector TEXT PRIMARY KEY,",
  "  connected INTEGER NOT NULL DEFAULT 0,",
  "  config_json TEXT",
  ");",
  "CREATE TABLE IF NOT EXISTS workspace_chats (",
  "  id TEXT PRIMARY KEY,",
  "  title TEXT NOT NULL,",
  "  messages_json TEXT NOT NULL,",
  "  session_memo_json TEXT NOT NULL DEFAULT '{}',",
  "  workflow_id TEXT,",
  "  created_at TEXT NOT NULL,",
  "  updated_at TEXT NOT NULL",
  ");",
  "CREATE TABLE IF NOT EXISTS workspace_chat_sources (",
  "  id TEXT PRIMARY KEY,",
  "  chat_id TEXT NOT NULL REFERENCES workspace_chats(id) ON DELETE CASCADE,",
  "  artifact_id TEXT NOT NULL,",
  "  file_name TEXT NOT NULL,",
  "  mime_type TEXT,",
  "  status TEXT NOT NULL,",
  "  engine TEXT,",
  "  document_artifact_id TEXT,",
  "  summary_json TEXT,",
  "  error_code TEXT,",
  "  error_message TEXT,",
  "  created_at TEXT NOT NULL,",
  "  updated_at TEXT NOT NULL",
  ");",
  "CREATE TABLE IF NOT EXISTS trigger_receipts (",
  "  dedupe_key TEXT PRIMARY KEY,",
  "  workflow_id TEXT NOT NULL,",
  "  trigger_type TEXT NOT NULL,",
  "  status TEXT NOT NULL,",
  "  execution_id TEXT,",
  "  created_at TEXT NOT NULL,",
  "  updated_at TEXT NOT NULL",
  ");",
  "CREATE INDEX IF NOT EXISTS idx_executions_started_at ON executions(started_at);",
  "CREATE INDEX IF NOT EXISTS idx_workspace_chat_sources_chat_id ON workspace_chat_sources(chat_id, created_at);",
  "CREATE TABLE IF NOT EXISTS work_discovery_sessions (",
  "  id TEXT PRIMARY KEY,",
  "  status TEXT NOT NULL,",
  "  revision INTEGER NOT NULL DEFAULT 0,",
  "  user_goal TEXT NOT NULL,",
  "  state_json TEXT NOT NULL,",
  "  published_workflow_id TEXT,",
  "  error_code TEXT,",
  "  error_message TEXT,",
  "  created_at TEXT NOT NULL,",
  "  updated_at TEXT NOT NULL",
  ");",
  "CREATE INDEX IF NOT EXISTS idx_discovery_status ON work_discovery_sessions(status, updated_at);",
  "CREATE TABLE IF NOT EXISTS work_discovery_examples (",
  "  id TEXT PRIMARY KEY,",
  "  session_id TEXT NOT NULL,",
  "  label TEXT,",
  "  output_artifact_ids_json TEXT NOT NULL,",
  "  input_artifact_ids_json TEXT NOT NULL,",
  "  observations_json TEXT NOT NULL DEFAULT '[]',",
  "  created_at TEXT NOT NULL,",
  "  FOREIGN KEY(session_id) REFERENCES work_discovery_sessions(id) ON DELETE CASCADE",
  ");",
  "CREATE TABLE IF NOT EXISTS work_discovery_snapshots (",
  "  id TEXT PRIMARY KEY,",
  "  session_id TEXT NOT NULL,",
  "  example_id TEXT NOT NULL,",
  "  source_id TEXT NOT NULL,",
  "  kind TEXT NOT NULL,",
  "  artifact_id TEXT,",
  "  manifest_path TEXT,",
  "  fingerprint TEXT NOT NULL,",
  "  query_json TEXT,",
  "  metadata_json TEXT,",
  "  captured_at TEXT NOT NULL,",
  "  FOREIGN KEY(session_id) REFERENCES work_discovery_sessions(id) ON DELETE CASCADE,",
  "  FOREIGN KEY(example_id) REFERENCES work_discovery_examples(id) ON DELETE CASCADE",
  ");",
  "CREATE TABLE IF NOT EXISTS work_discovery_replay_cases (",
  "  id TEXT PRIMARY KEY,",
  "  session_id TEXT NOT NULL,",
  "  example_id TEXT NOT NULL,",
  "  snapshot_set_id TEXT NOT NULL,",
  "  expected_observations_json TEXT NOT NULL,",
  "  last_result_json TEXT,",
  "  created_at TEXT NOT NULL,",
  "  FOREIGN KEY(session_id) REFERENCES work_discovery_sessions(id) ON DELETE CASCADE,",
  "  FOREIGN KEY(example_id) REFERENCES work_discovery_examples(id) ON DELETE CASCADE",
  ");",
  "CREATE TABLE IF NOT EXISTS workflow_repair_proposals (",
  "  id TEXT PRIMARY KEY,",
  "  workflow_id TEXT NOT NULL REFERENCES workflows(id) ON DELETE CASCADE,",
  "  base_version INTEGER NOT NULL,",
  "  status TEXT NOT NULL,",
  "  dedupe_key TEXT NOT NULL UNIQUE,",
  "  proposal_json TEXT NOT NULL,",
  "  applied_version INTEGER,",
  "  created_at TEXT NOT NULL,",
  "  updated_at TEXT NOT NULL",
  ");",
  "CREATE INDEX IF NOT EXISTS idx_workflow_repair_proposals_workflow ON workflow_repair_proposals(workflow_id, created_at);",
].join('\n');
