import type { AxCommandDefinition, AxCommandLifecycle } from '../../schema.js';

export const CORE_COMMAND_DEFINITIONS = [
  {
    name: 'command.list',
    lifecycle: 'read',
    description: '이 세션에서 사용할 수 있는 AX 명령 목록을 조회합니다.',
    args: {},
    mutates: false,
  },
  {
    name: 'resource.list',
    lifecycle: 'read',
    description: '연결 상태를 노출하는 안전한 리소스 목록을 조회합니다.',
    args: {},
    mutates: false,
  },
  {
    name: 'http.list',
    lifecycle: 'read',
    description: '저장된 HTTP REST 연결과 명시적 선택에 필요한 상태를 조회합니다. 인증 비밀은 반환하지 않습니다.',
    args: {},
    mutates: false,
  },
  {
    name: 'source.list',
    lifecycle: 'read',
    description: '연결된 Gmail·Slack·로컬 폴더의 실제 source 목록을 조회합니다.',
    args: { connector: 'connector id (optional)' },
    mutates: false,
  },
  {
    name: 'source.files.list',
    lifecycle: 'read',
    description: '연결된 로컬 폴더의 파일 목록을 조회합니다.',
    args: { folderId: 'connected folder id', extensions: 'array or comma-separated extensions' },
    mutates: false,
  },
  {
    name: 'source.file.read',
    lifecycle: 'read',
    description: '연결된 로컬 폴더 안 PDF의 제한된 본문과 citation을 읽습니다.',
    args: { folderId: 'connected folder id', path: 'file path returned by source.files.list', maxChars: '1000..20000' },
    mutates: false,
  },
  {
    name: 'source.search',
    lifecycle: 'read',
    description: '연결된 로컬 폴더의 검색 인덱스를 조회합니다.',
    args: { query: 'search query', folderId: 'connected folder id', limit: 'positive integer' },
    mutates: false,
  },
  {
    name: 'session.source.list',
    lifecycle: 'read',
    description: '현재 대화 세션에 업로드된 자료와 문서 엔진 상태를 조회합니다.',
    args: {},
    mutates: false,
  },
  {
    name: 'session.source.read',
    lifecycle: 'read',
    description: '현재 대화 세션의 준비된 문서에서 제한된 Docling 본문과 페이지 근거를 읽습니다.',
    args: { sourceId: 'session.source.list에서 반환한 source id', maxChars: '1000..20000' },
    mutates: false,
  },
  {
    name: 'capability.list',
    lifecycle: 'read',
    description: '현재 연결 상태에서 사용할 수 있는 capability를 조회합니다.',
    args: { connector: 'connector id', kind: 'read | write | trigger' },
    mutates: false,
  },
  {
    name: 'capability.describe',
    lifecycle: 'read',
    description: '하나의 capability 계약과 필요한 파라미터를 조회합니다.',
    args: { id: 'catalog capability id' },
    mutates: false,
  },
  {
    name: 'capability.invoke',
    lifecycle: 'read',
    description: '읽기 전용 capability를 실행합니다. 쓰기 capability는 거부됩니다.',
    args: { id: 'read capability id', params: 'capability parameters' },
    mutates: false,
  },
  {
    name: 'workflow.list',
    lifecycle: 'read',
    description: '저장된 workflow의 식별자와 최신 버전을 조회합니다.',
    args: {},
    mutates: false,
  },
  {
    name: 'workflow.inspect',
    lifecycle: 'read',
    description: '저장된 workflow의 최신 IR과 검증 상태를 조회합니다.',
    args: { workflowId: 'workflow id' },
    mutates: false,
  },
  {
    name: 'workflow.validate',
    lifecycle: 'read',
    description: 'workflow schema, capability 계약, 연결 상태를 검증합니다.',
    args: { workflowId: 'workflow id' },
    mutates: false,
  },
  {
    name: 'report.generate',
    lifecycle: 'ephemeral',
    description: '현재 대화의 빈 PDF 양식과 완성 예시를 연결된 읽기 전용 API/DB 데이터로 재현해 다음 기간 보고서를 생성합니다.',
    args: {
      goal: '사용자의 전체 보고서 요청',
      templateSourceId: '현재 대화에 업로드된 빈 PDF 양식 source id',
      exampleSourceId: '현재 대화에 업로드된 완성 PDF 예시 source id',
      resumeExecutionId: '선택: 사용자가 실패한 보고서를 이어서 재시도하도록 요청한 경우 그 실행 ID. 원래 goal과 자료를 유지. 새 보고서 요청에는 사용하지 않음.',
    },
    mutates: true,
  },
] as const satisfies readonly (AxCommandDefinition & { lifecycle: AxCommandLifecycle })[];
