param(
  [Parameter(Mandatory = $true)][string]$Installer,
  [string]$PreviousInstaller,
  [string]$PreviousRepo,
  [switch]$DryRun
)
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
$guard = Join-Path $PSScriptRoot 'runner-safety.mjs'
if ($DryRun) {
  # Deliberately does not resolve or execute either installer, create a marker,
  # enumerate registry/credentials, or clean up anything on the host.
  & node $guard --dry-run
  if ($LASTEXITCODE -ne 0) { throw 'Safety dry-run failed.' }
  Write-Output '[installer] Dry-run only: clean install -> restart -> same-version reinstall -> uninstall retention -> reinstall recovery; optional pinned preview upgrade.'
  return
}
$contextJson = & node $guard
if ($LASTEXITCODE -ne 0) { throw 'Installer requires a marked disposable GitHub-hosted Windows runner.' }
$context = $contextJson | ConvertFrom-Json
$repo = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '../..')).Path
$installerPath = (Resolve-Path -LiteralPath $Installer).Path
$currentSha = $env:GITHUB_SHA
$previewSha = '0ba5e22f54cc9fe2bb777f085290bb03de5f457b'
$package = Get-Content -LiteralPath (Join-Path $repo 'apps/desktop/package.json') -Raw | ConvertFrom-Json
$builder = Get-Content -LiteralPath (Join-Path $repo 'apps/desktop/electron-builder.yml') -Raw | ConvertFrom-Json
if ($builder.appId -cne 'com.axstudio.desktop' -or $builder.productName -cne 'AX Studio') { throw 'Application identity changed; safety guard review required.' }
if ([bool]$PreviousInstaller -ne [bool]$PreviousRepo) { throw 'PreviousInstaller and PreviousRepo are required together.' }
$initialRepo = $repo
$initialSha = $currentSha
$initialInstaller = $installerPath
if ($PreviousInstaller) {
  $initialRepo = (Resolve-Path -LiteralPath $PreviousRepo).Path
  $initialInstaller = (Resolve-Path -LiteralPath $PreviousInstaller).Path
  $initialSha = $previewSha
  $previousPackage = Get-Content -LiteralPath (Join-Path $initialRepo 'apps/desktop/package.json') -Raw | ConvertFrom-Json
  if ($previousPackage.version -cne '0.1.0-preview.1' -or $package.version -ceq $previousPackage.version) { throw 'A distinct pinned preview version is required.' }
}
# Exact UUID v5 generated by electron-builder for com.axstudio.desktop.
$appGuid = '45355cef-5094-5e47-adc3-1337b8e2577e'
$registryKeys = @(foreach ($hive in @('HKCU:', 'HKLM:')) {
  foreach ($software in @('Software', 'Software\WOW6432Node')) {
    "$hive\$software\$appGuid"
    "$hive\$software\Microsoft\Windows\CurrentVersion\Uninstall\$appGuid"
  }
})
$shortcutPaths = @(foreach ($folder in @('DesktopDirectory', 'CommonDesktopDirectory', 'Programs', 'CommonPrograms')) {
  $location = [Environment]::GetFolderPath($folder)
  if ($location) { Join-Path $location 'AX Studio.lnk' }
})
$cache = Join-Path $env:LOCALAPPDATA '@ax-studiodesktop-updater'
foreach ($path in $registryKeys + $shortcutPaths + @($cache)) {
  if (Test-Path -LiteralPath $path) { throw 'Refusing an existing AX Studio installation/registration/cache/shortcut.' }
}
if (Get-Process -Name 'AX Studio' -ErrorAction SilentlyContinue) { throw 'An AX Studio process already exists.' }
$installDir = $context.install
$executable = Join-Path $installDir 'AX Studio.exe'
$uninstaller = Join-Path $installDir 'Uninstall AX Studio.exe'
$installKey = "HKCU:\Software\$appGuid"
$uninstallKey = "HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall\$appGuid"
$script:uninstallerHash = $null
$script:exitUnconfirmed = $false
$script:owned = $false
$script:installedRepo = $null
$script:installedSha = $null
$passed = $false

function Assert-Runner {
  & node $guard --path $installDir --path $context.acceptance | Out-Null
  if ($LASTEXITCODE -ne 0) { throw 'Runner/path ownership changed.' }
}
function Assert-Asset([string]$SourceRepo, [string]$SourceSha, [string]$Asset) {
  & node (Join-Path $PSScriptRoot 'verify-assets.mjs') --repo $SourceRepo --source-sha $SourceSha --manifest (Join-Path $SourceRepo 'apps/desktop/release/installation-manifest.json') --installer $Asset
  if ($LASTEXITCODE -ne 0) { throw 'Refusing an unverified installer asset.' }
}
function Assert-OwnedInstall([string]$Version) {
  Assert-Runner
  foreach ($key in @($installKey, $uninstallKey)) {
    if (-not (Test-Path -LiteralPath $key)) { throw 'Owned per-user installation registration is missing.' }
    $location = (Get-ItemProperty -LiteralPath $key).InstallLocation
    if (-not $location -or [IO.Path]::GetFullPath($location).TrimEnd('\') -ine $installDir) { throw 'Another installation owns the registry; refusing all cleanup.' }
  }
  $registration = Get-ItemProperty -LiteralPath $uninstallKey
  if ($registration.DisplayName -cne 'AX Studio' -or $registration.DisplayVersion -cne $Version) { throw 'Installed registration identity/version mismatch.' }
  $script:owned = $true
}
function Run-Installer([string]$Path, [string]$Arguments) {
  Assert-Runner
  & node $guard --path $Path | Out-Null
  if ($LASTEXITCODE -ne 0) { throw 'Installer/uninstaller executable path is not owned.' }
  $process = Start-Process -FilePath $Path -ArgumentList $Arguments -WindowStyle Hidden -PassThru
  if (-not $process.WaitForExit(180000)) {
    $script:exitUnconfirmed = $true
    throw 'Installer exit unconfirmed; no cleanup/retry will run. Dispose this runner and retain evidence.'
  }
  if ($process.ExitCode -ne 0) { throw "Installer failed: exit=$($process.ExitCode)." }
}
function Install-App([string]$SourceRepo, [string]$SourceSha, [string]$Asset) {
  Assert-Asset $SourceRepo $SourceSha $Asset
  Run-Installer $Asset "/S /currentuser --no-desktop-shortcut /D=$installDir"
  $version = (Get-Content -LiteralPath (Join-Path $SourceRepo 'apps/desktop/package.json') -Raw | ConvertFrom-Json).version
  Assert-OwnedInstall $version
  & (Join-Path $PSScriptRoot 'package-metadata.ps1') -Repo $SourceRepo -SourceSha $SourceSha -InstalledDirectory $installDir
  $script:uninstallerHash = (Get-FileHash -LiteralPath $uninstaller -Algorithm SHA256).Hash
  $script:installedRepo = $SourceRepo
  $script:installedSha = $SourceSha
}
function Test-App([string]$Stage, [string]$Version, [switch]$Reopen, [switch]$Upgrade) {
  Assert-OwnedInstall $Version
  $arguments = @((Join-Path $PSScriptRoot 'installed-app.mjs'), '--executable', $executable, '--workspace', $context.acceptance,
    '--fixture-repo', $initialRepo, '--fixture-sha', $initialSha, '--version', $Version, '--stage', $Stage)
  if ($Reopen) { $arguments += '--reopen' }
  if ($Upgrade) { $arguments += '--upgrade' }
  & node @arguments
  if ($LASTEXITCODE -ne 0) { throw "Installed application acceptance failed at $Stage; inspect its stage evidence." }
}
function Uninstall-App([string]$Version) {
  Assert-OwnedInstall $Version
  if (-not $script:uninstallerHash -or (Get-FileHash -LiteralPath $uninstaller -Algorithm SHA256).Hash -cne $script:uninstallerHash) { throw 'Owned uninstaller bytes changed.' }
  # _?= prevents NSIS self-copy/relaunch; WaitForExit observes the real uninstall.
  Run-Installer $uninstaller "/S /currentuser _?=$installDir"
  if (Test-Path -LiteralPath $executable) { throw 'Program survived uninstall.' }
  & node (Join-Path $PSScriptRoot 'verify-assets.mjs') --repo $script:installedRepo --source-sha $script:installedSha --manifest (Join-Path $script:installedRepo 'apps/desktop/release/installation-manifest.json') --installed $installDir --removed
  if ($LASTEXITCODE -ne 0) { throw 'Installed payload survived uninstall.' }
  foreach ($path in $registryKeys + $shortcutPaths) { if (Test-Path -LiteralPath $path) { throw 'Uninstall left registration/shortcut.' } }
  $script:owned = $false
}

Assert-Asset $repo $currentSha $installerPath
Assert-Asset $initialRepo $initialSha $initialInstaller
$installedVersion = if ($PreviousInstaller) { '0.1.0-preview.1' } else { $package.version }
try {
  Install-App $initialRepo $initialSha $initialInstaller
  & node (Join-Path $PSScriptRoot 'clean-startup.mjs') --executable $executable --version $installedVersion
  if ($LASTEXITCODE -ne 0) { throw 'Virgin installed-app startup failed; inspect clean-startup evidence.' }
  Test-App 'initial' $installedVersion
  Test-App 'restart' $installedVersion -Reopen
  Install-App $repo $currentSha $installerPath
  $installedVersion = $package.version
  if ($PreviousInstaller) { Test-App 'upgrade' $installedVersion -Reopen -Upgrade }
  else { Test-App 'same-version-reinstall' $installedVersion -Reopen }
  # The upgrade job also exercises same-version current reinstall after upgrade.
  if ($PreviousInstaller) { Install-App $repo $currentSha $installerPath; Test-App 'same-version-reinstall' $installedVersion -Reopen -Upgrade }
  & node (Join-Path $PSScriptRoot 'retained-data.mjs') --workspace $context.acceptance --snapshot
  if ($LASTEXITCODE -ne 0) { throw 'Retention snapshot failed.' }
  Uninstall-App $installedVersion
  & node (Join-Path $PSScriptRoot 'retained-data.mjs') --workspace $context.acceptance --compare
  if ($LASTEXITCODE -ne 0) { throw 'Uninstall changed synthetic data.' }
  Install-App $repo $currentSha $installerPath
  Test-App 'reinstall-recovery' $installedVersion -Reopen -Upgrade:([bool]$PreviousInstaller)
  & node (Join-Path $PSScriptRoot 'retained-data.mjs') --workspace $context.acceptance --snapshot --phase final
  if ($LASTEXITCODE -ne 0) { throw 'Final retention snapshot failed.' }
  Uninstall-App $installedVersion
  & node (Join-Path $PSScriptRoot 'retained-data.mjs') --workspace $context.acceptance --compare --phase final
  if ($LASTEXITCODE -ne 0) { throw 'Final uninstall changed synthetic data.' }
  $passed = $true
} finally {
  if ($script:owned -and -not $script:exitUnconfirmed) { Uninstall-App $installedVersion }
  # Never delete a cache, registry entry, user profile or retained data manually.
  Write-Output "[installer] passed=$passed; installer_exit_confirmed=$(-not $script:exitUnconfirmed); evidence retained in the job-owned runner temp directory."
}
