export const SLOT_LABELS: Record<string, string> = {
  goal: '지시 의도',
  trigger: '트리거',
  'trigger.schedule': '스케줄',
  'trigger.timezone': '타임존',
  source: '데이터 소스',
  filter: '필터/조건',
  action: '실행 액션',
  exception: '예외 처리',
  approval: '승인',
  permission: '권한',
  completion: '완료 조건',
  'slack.channel': 'Slack 채널',
  'gmail.account': 'Gmail 계정',
  'local_file.path': '로컬 파일',
  'rdb.connection': 'DB 연결',
  'report.template': '리포트 템플릿',
  'ai_decision.schema': 'AI 출력 스키마',
};
