import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { describe, expect, it } from 'vitest';
import { ArtifactStore } from '../artifact-store.js';

describe('ArtifactStore content and deduplication', () => {
  it('deduplicates imports by sha256', () => {
    const root = mkdtempSync(join(tmpdir(), 'ax-artifacts-'));
    const store = new ArtifactStore(root);
    const source = join(root, 'sample.txt');
    writeFileSync(source, 'fixture content');

    const first = store.importFile(source);
    const second = store.importFile(source);
    expect(second.id).toBe(first.id);
    expect(second.sha256).toBe(first.sha256);
  });

  it('persists generated bytes with a safe file name and deduplicates by sha256', () => {
    const root = mkdtempSync(join(tmpdir(), 'ax-artifacts-'));
    const store = new ArtifactStore(root);
    const bytes = Buffer.from('%PDF-1.7 fixture');

    const first = store.putBytes(bytes, {
      fileName: '..\\unsafe/report?.pdf',
      mimeType: 'application/pdf',
    });

    expect(first.fileName).toBe('report_.pdf');
    expect(first.storedPath).toBe(join(root, `${first.id}_report_.pdf`));
    expect(readFileSync(first.storedPath)).toEqual(bytes);
    expect(store.get(first.id)).toEqual(first);

    const duplicate = store.putBytes(Buffer.from(bytes), {
      fileName: 'different-name.pdf',
      mimeType: 'application/pdf',
    });
    expect(duplicate).toEqual(first);
  });

  it('rejects conflicting generated IDs instead of overwriting their content', () => {
    const root = mkdtempSync(join(tmpdir(), 'ax-artifacts-'));
    const store = new ArtifactStore(root);
    store.putBytes(Buffer.from('first'), { id: 'report_1', fileName: 'report.pdf' });

    expect(() => store.putBytes(Buffer.from('second'), { id: 'report_1', fileName: 'report.pdf' })).toThrow(
      'already exists with different content',
    );
    expect(() => store.putBytes(Buffer.from('third'), { id: '../escaped', fileName: 'report.pdf' })).toThrow(
      'Invalid artifact id',
    );
  });
});
