import type { AxCommandDefinition, AxCommandLifecycle } from '../../schema.js';

const WORKFLOW_STEPS_INPUT = 'Array of step objects, not capability IDs. Action fields: type="action", unique id, connector, action (required even with optional actionRef), params object. Use type="ai_decision" with a goal between read and notification actions when the user asks to summarize, classify, filter, or transform data; do not put placeholder text in a send action. Inspect the selected capability for its connector/action and parameter contract. Shape example only; replace recipient and content with the user\'s request: [{"type":"action","id":"send_mail","connector":"gmail","action":"message.send","params":{"to":"recipient@example.com","subject":"Example subject","body":"Example body"}}]. Runtime determines side effects and requires approval before external sends; do not bypass it through capability.invoke.';

export const WORKFLOW_COMMAND_DEFINITIONS = [
  {
    name: 'workflow.create',
    lifecycle: 'workflow',
    description: '새 workflow를 즉시 저장합니다. 변경 후 자동으로 새 버전을 만듭니다.',
    args: { name: 'workflow name', goal: 'workflow goal', trigger: 'trigger object', steps: WORKFLOW_STEPS_INPUT },
    mutates: true,
  },
  {
    name: 'workflow.update',
    lifecycle: 'workflow',
    description: 'workflow의 허용된 필드와 개별 step을 수정하고 즉시 저장합니다.',
    args: { workflowId: 'workflow id', baseVersion: 'last inspected version', operations: 'set/upsert_step/remove_step list' },
    mutates: true,
  },
  {
    name: 'workflow.delete',
    lifecycle: 'workflow',
    description: '확인한 버전의 workflow를 삭제합니다.',
    args: { workflowId: 'workflow id', baseVersion: 'last inspected version' },
    mutates: true,
  },
  {
    name: 'workflow.run',
    lifecycle: 'run',
    description: '저장된 workflow를 수동 실행합니다. runtime 승인 정책을 그대로 적용합니다.',
    args: { workflowId: 'workflow id returned by workflow.list' },
    mutates: true,
  },
  {
    name: 'execution.enqueue_once',
    lifecycle: 'ephemeral',
    description: '검증된 계획을 저장하지 않고 일회 실행 큐에 등록합니다. 원래 대화 세션이 있으면 진행·완료 결과를 대화에도 남기고 Activity와 approval 로그에도 기록합니다.',
    args: { name: '실행 이름', goal: '실행 목적', trigger: '선택적 trigger', steps: WORKFLOW_STEPS_INPUT },
    mutates: true,
  },
  {
    name: 'execution.explain',
    lifecycle: 'read',
    description: '실행이 기술적으로 끝났는지와 결과 품질이 왜 통과·차단되었는지 안전하게 설명합니다.',
    args: { executionId: 'execution id' },
    mutates: false,
  },
  {
    name: 'repair.list',
    lifecycle: 'read',
    description: 'schema drift에서 생성된 보수적 repair 제안 목록을 조회합니다.',
    args: { workflowId: 'workflow id (optional)', status: 'proposed | applied | rejected (optional)' },
    mutates: false,
  },
  {
    name: 'repair.inspect',
    lifecycle: 'read',
    description: 'repair 후보와 과거 replay 결과를 조회합니다. 조회만으로 workflow는 변경되지 않습니다.',
    args: { repairId: 'repair.list에서 반환한 repair id' },
    mutates: false,
  },
  {
    name: 'repair.apply',
    lifecycle: 'workflow',
    description: '모든 과거 replay를 통과한 선택 후보만 새 workflow 버전으로 적용합니다.',
    args: { repairId: 'repair id', candidateId: 'candidate id', baseVersion: '확인한 workflow version' },
    mutates: true,
  },
  {
    name: 'repair.reject',
    lifecycle: 'workflow',
    description: 'repair 제안을 적용하지 않기로 기록합니다.',
    args: { repairId: 'repair id', baseVersion: '확인한 workflow version', reason: '거부 사유 (optional)' },
    mutates: true,
  },
  {
    name: 'job.propose',
    lifecycle: 'workflow',
    description: '반복·이벤트 업무 초안을 검증하고 확인 카드를 보여줍니다. 이 명령은 workflow를 저장하지 않습니다. HTTP 조회 업무는 fetch/notify를 사용하고, Gmail·Slack·폴더 등 일반 업무는 trigger와 steps를 함께 사용합니다.',
    args: {
      name: '업무 이름',
      goal: '업무 목적',
      schedule: 'cron과 timezone (기본 0 21 * * *, Asia/Seoul)',
      fetch: 'HTTP GET path, 선택 headers, HTTP가 여러 개면 connectionId',
      interpret: '조회 결과를 요약하는 AI 목표',
      notify: 'Slack channel과 skipIfEmpty',
      trigger: 'HTTP가 아닌 업무의 시작 조건: gmail.new_message, slack.new_message, local_folder.new_file 등',
      steps: WORKFLOW_STEPS_INPUT,
      runOnceNow: '저장 직후 한 번 실행',
      allowExternalAuto: '확인 후 Slack 자동 발송',
    },
    mutates: false,
  },
  {
    name: 'job.commit',
    lifecycle: 'workflow',
    description: 'host 확인 카드 이후에만 초안 workflow를 저장하고 스케줄을 켭니다. agent가 직접 호출하지 않습니다.',
    args: {},
    mutates: true,
  },
  {
    name: 'context.update',
    lifecycle: 'context',
    description: '사용자가 확인한 임시 합의나 저장 workflow의 업무 기준을 context metadata로 저장합니다. Runtime 권한과 실행 계약은 바꾸지 않습니다.',
    args: { scope: 'session | workflow', set: 'bounded string fields', remove: 'field names to remove', confirmed: 'host-confirmed UI response' },
    mutates: true,
  },
  {
    name: 'ui.present',
    lifecycle: 'present',
    description: '필요할 때만 검토·선택·입력을 위한 안전한 UI 카드를 대화에 표시합니다. 외부 작업은 실행하지 않습니다.',
    args: { title: '카드 제목', blocks: '근거·판단·단계·안내 블록', inputs: '필요한 입력 목록', actions: '사용자 응답 버튼 목록' },
    mutates: false,
  },
] as const satisfies readonly (AxCommandDefinition & { lifecycle: AxCommandLifecycle })[];
